<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticlesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Populates the articles table with initial data.
     */
    public function run()
    {
        DB::table('articles')->insert([
            [
                'id' => 1,
                'reference' => 'ail-en-vrac-1',
                'designation' => 'Ail en vrac',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 2,
                'reference' => 'artichauts-2',
                'designation' => 'Artichauts',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 3,
                'reference' => 'asperge-frais-3',
                'designation' => 'Asperge frais',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'botte',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 4,
                'reference' => 'aubergine-4',
                'designation' => 'Aubergine',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 5,
                'reference' => 'basilic-frais-5',
                'designation' => 'Basilic frais',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'botte',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 6,
                'reference' => 'betteraves-6',
                'designation' => 'Betteraves sans branches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 7,
                'reference' => 'brocolis-7',
                'designation' => 'Brocolis',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 8,
                'reference' => 'cardon-8',
                'designation' => 'Cardon',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 9,
                'reference' => 'carottes-9',
                'designation' => 'Carottes sans branches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 10,
                'reference' => 'celeri-branche-10',
                'designation' => 'Cèleri en branches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 11,
                'reference' => 'citron-frais-11',
                'designation' => 'Citron frais',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 12,
                'reference' => 'concombre-12',
                'designation' => 'Concombre',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 13,
                'reference' => 'courgettes-13',
                'designation' => 'Courgettes vertes longues',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 14,
                'reference' => 'epinards-14',
                'designation' => 'Epinards frais',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 15,
                'reference' => 'haricot-vert-15',
                'designation' => 'Haricot vert frais',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 16,
                'reference' => 'oignons-16',
                'designation' => 'Oignons sans branches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 17,
                'reference' => 'pomme-de-terre-17',
                'designation' => 'Pomme de terre',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 18,
                'reference' => 'tomates-18',
                'designation' => 'Tomates fraîches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 19,
                'reference' => 'abricots-19',
                'designation' => 'Abricots',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 20,
                'reference' => 'bananes-20',
                'designation' => 'Bananes',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 21,
                'reference' => 'fraises-21',
                'designation' => 'Fraises',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 22,
                'reference' => 'oranges-22',
                'designation' => 'Oranges de table',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 23,
                'reference' => 'pommes-23',
                'designation' => 'Pommes fruit',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:03',
                'updated_at' => '2025-09-29 10:18:03'
            ],
            [
                'id' => 100,
                'reference' => 'abricots-secs-100',
                'designation' => 'Abricots secs',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 101,
                'reference' => 'amandes-101',
                'designation' => 'Amandes grosses décortiquées',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 102,
                'reference' => 'beurre-beldi-102',
                'designation' => 'Beurre Beldi',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 103,
                'reference' => 'ble-dur-103',
                'designation' => 'Blé dur concassé (Herbel)',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 104,
                'reference' => 'cacahuetes-104',
                'designation' => 'Cacahuètes décortiquées',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 105,
                'reference' => 'couscous-105',
                'designation' => 'Couscous en vrac 1er choix',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 106,
                'reference' => 'dattes-106',
                'designation' => 'Dattes 1er choix',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 107,
                'reference' => 'farine-107',
                'designation' => 'Farine blé dur',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 108,
                'reference' => 'lentilles-108',
                'designation' => 'Lentilles en vrac (Nylon)',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 109,
                'reference' => 'miel-109',
                'designation' => 'Miel',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 110,
                'reference' => 'huile-olive-110',
                'designation' => 'Huile d’olive extra vierge',
                'description' => '',
                'categorie_id' => 2,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'L',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:19',
                'updated_at' => '2025-09-29 10:18:19'
            ],
            [
                'id' => 200,
                'reference' => 'cervelle-boeuf-200',
                'designation' => 'Cervelle de bœuf 300-400 g',
                'description' => '',
                'categorie_id' => 3,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'pc',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:49',
                'updated_at' => '2025-09-29 10:18:49'
            ],
            [
                'id' => 201,
                'reference' => 'contre-filet-201',
                'designation' => 'Contre filet de bœuf',
                'description' => '',
                'categorie_id' => 3,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:49',
                'updated_at' => '2025-09-29 10:18:49'
            ],
            [
                'id' => 202,
                'reference' => 'cuise-boeuf-202',
                'designation' => 'Cuise de bœuf désossée',
                'description' => '',
                'categorie_id' => 3,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:49',
                'updated_at' => '2025-09-29 10:18:49'
            ],
            [
                'id' => 203,
                'reference' => 'filet-boeuf-203',
                'designation' => 'Filet de bœuf paré',
                'description' => '',
                'categorie_id' => 3,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:49',
                'updated_at' => '2025-09-29 10:18:49'
            ],
            [
                'id' => 204,
                'reference' => 'foie-boeuf-204',
                'designation' => 'Foie de bœuf',
                'description' => '',
                'categorie_id' => 3,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:49',
                'updated_at' => '2025-09-29 10:18:49'
            ],
            [
                'id' => 205,
                'reference' => 'mouton-205',
                'designation' => 'Mouton entier',
                'description' => '',
                'categorie_id' => 3,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:18:49',
                'updated_at' => '2025-09-29 10:18:49'
            ],
            [
                'id' => 300,
                'reference' => 'coquelet-300',
                'designation' => 'Coquelet de 400 g à 500 g',
                'description' => '',
                'categorie_id' => 4,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:20',
                'updated_at' => '2025-09-29 10:19:20'
            ],
            [
                'id' => 301,
                'reference' => 'filet-dinde-301',
                'designation' => 'Filet de dinde',
                'description' => '',
                'categorie_id' => 4,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:20',
                'updated_at' => '2025-09-29 10:19:20'
            ],
            [
                'id' => 302,
                'reference' => 'oeuf-caille-302',
                'designation' => 'Œuf de caille (paquet de 18)',
                'description' => '',
                'categorie_id' => 4,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'pt',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:20',
                'updated_at' => '2025-09-29 10:19:20'
            ],
            [
                'id' => 303,
                'reference' => 'oeuf-l-303',
                'designation' => 'Œuf L (0,63 / 73 g)',
                'description' => '',
                'categorie_id' => 4,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'pce',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:20',
                'updated_at' => '2025-09-29 10:19:20'
            ],
            [
                'id' => 304,
                'reference' => 'pigeon-304',
                'designation' => 'Pigeon entier vidé',
                'description' => '',
                'categorie_id' => 4,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'pce',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:20',
                'updated_at' => '2025-09-29 10:19:20'
            ],
            [
                'id' => 305,
                'reference' => 'poulet-305',
                'designation' => 'Poulet d’élevage vidé',
                'description' => '',
                'categorie_id' => 4,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:20',
                'updated_at' => '2025-09-29 10:19:20'
            ],
            [
                'id' => 400,
                'reference' => 'anchois-400',
                'designation' => 'Anchois frais',
                'description' => '',
                'categorie_id' => 5,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:52',
                'updated_at' => '2025-09-29 10:19:52'
            ],
            [
                'id' => 401,
                'reference' => 'calamar-401',
                'designation' => 'Calamar entier',
                'description' => '',
                'categorie_id' => 5,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:52',
                'updated_at' => '2025-09-29 10:19:52'
            ],
            [
                'id' => 402,
                'reference' => 'chinchard-402',
                'designation' => 'Chinchard',
                'description' => '',
                'categorie_id' => 5,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:52',
                'updated_at' => '2025-09-29 10:19:52'
            ],
            [
                'id' => 403,
                'reference' => 'congre-403',
                'designation' => 'Congre',
                'description' => '',
                'categorie_id' => 5,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:52',
                'updated_at' => '2025-09-29 10:19:52'
            ],
            [
                'id' => 404,
                'reference' => 'crevettes-decortiquees-404',
                'designation' => 'Crevettes décortiquées',
                'description' => '',
                'categorie_id' => 5,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:52',
                'updated_at' => '2025-09-29 10:19:52'
            ],
            [
                'id' => 405,
                'reference' => 'espadon-405',
                'designation' => 'Espadon en filet',
                'description' => '',
                'categorie_id' => 5,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:52',
                'updated_at' => '2025-09-29 10:19:52'
            ],
            [
                'id' => 406,
                'reference' => 'merlan-406',
                'designation' => 'Merlan ration',
                'description' => '',
                'categorie_id' => 5,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:52',
                'updated_at' => '2025-09-29 10:19:52'
            ],
            [
                'id' => 407,
                'reference' => 'sardine-407',
                'designation' => 'Sardine',
                'description' => '',
                'categorie_id' => 5,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:52',
                'updated_at' => '2025-09-29 10:19:52'
            ],
            [
                'id' => 408,
                'reference' => 'thon-408',
                'designation' => 'Filet de thon frais',
                'description' => '',
                'categorie_id' => 5,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:19:52',
                'updated_at' => '2025-09-29 10:19:52'
            ],
            [
                'id' => 409,
                'reference' => 'betteraves-sans-branches-6',
                'designation' => 'Betteraves sans branches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 410,
                'reference' => 'carottes-sans-branches-9',
                'designation' => 'Carottes sans branches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 411,
                'reference' => 'celeri-en-branches-10',
                'designation' => 'Cèleri en branches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 412,
                'reference' => 'celeri-rave-11',
                'designation' => 'Cèleri rave',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 413,
                'reference' => 'champignon-cepes-12',
                'designation' => 'Champignon cèpes',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 414,
                'reference' => 'champignon-de-paris-frais-13',
                'designation' => 'Champignon de paris frais',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 415,
                'reference' => 'choux-de-bruxelles-14',
                'designation' => 'Choux de Bruxelles',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 416,
                'reference' => 'choux-fleur-15',
                'designation' => 'Choux fleur',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 417,
                'reference' => 'choux-rouges-16',
                'designation' => 'Choux rouges',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 418,
                'reference' => 'choux-vert-17',
                'designation' => 'Choux vert',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 419,
                'reference' => 'concombre-18',
                'designation' => 'Concombre',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 420,
                'reference' => 'courgettes-vertes-longues-19',
                'designation' => 'Courgettes vertes longues',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 421,
                'reference' => 'epinards-20',
                'designation' => 'Epinards frais',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 422,
                'reference' => 'fenouil-21',
                'designation' => 'Fenouil frais',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 423,
                'reference' => 'haricot-vert-22',
                'designation' => 'Haricot vert frais',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 424,
                'reference' => 'oignons-23',
                'designation' => 'Oignons sans branches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 425,
                'reference' => 'pomme-de-terre-24',
                'designation' => 'Pomme de terre',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 426,
                'reference' => 'tomates-25',
                'designation' => 'Tomates fraîches',
                'description' => '',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 427,
                'reference' => 'abricots-26',
                'designation' => 'Abricots',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 428,
                'reference' => 'ananas-27',
                'designation' => 'Ananas',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 429,
                'reference' => 'avocat-28',
                'designation' => 'Avocat',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 430,
                'reference' => 'bananes-29',
                'designation' => 'Bananes',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 431,
                'reference' => 'cerises-30',
                'designation' => 'Cerises',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 432,
                'reference' => 'clementines-31',
                'designation' => 'Clémentines',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 433,
                'reference' => 'fraises-32',
                'designation' => 'Fraises',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 434,
                'reference' => 'framboises-33',
                'designation' => 'Framboises',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 435,
                'reference' => 'grenades-34',
                'designation' => 'Grenades',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 436,
                'reference' => 'kiwis-35',
                'designation' => 'Kiwis',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 437,
                'reference' => 'mangues-36',
                'designation' => 'Mangues',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 438,
                'reference' => 'melons-37',
                'designation' => 'Melons',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 439,
                'reference' => 'oranges-38',
                'designation' => 'Oranges',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 440,
                'reference' => 'pamplemousses-39',
                'designation' => 'Pamplemousses',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 441,
                'reference' => 'pasteques-40',
                'designation' => 'Pastèques',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 442,
                'reference' => 'peches-41',
                'designation' => 'Pêches',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 443,
                'reference' => 'poires-42',
                'designation' => 'Poires',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 444,
                'reference' => 'pommes-43',
                'designation' => 'Pommes',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 445,
                'reference' => 'prunes-44',
                'designation' => 'Prunes',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 446,
                'reference' => 'raisins-45',
                'designation' => 'Raisins',
                'description' => '',
                'categorie_id' => 6,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 0,
                'seuil_maximal' => 0,
                'est_actif' => 1,
                'created_at' => '2025-09-29 10:57:57',
                'updated_at' => '2025-09-29 10:57:57'
            ],
            [
                'id' => 447,
                'reference' => 'AAA',
                'designation' => 'AAAAAAA',
                'description' => 'AAAAAAAAAAAAAAAAAAAA',
                'categorie_id' => 1,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'unite_mesure' => 'kg',
                'seuil_minimal' => 20,
                'seuil_maximal' => 139,
                'est_actif' => 1,
                'created_at' => '2025-09-29 18:38:25',
                'updated_at' => '2025-09-29 18:38:25'
            ]
        ]);
    }
}