<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BonCommandesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Populates the bon_commandes table with initial data.
     */
    public function run()
    {
        DB::table('bon_commandes')->insert([
            [
                'id' => 9,
                'reference' => 'BC07/2025',
                'objet' => 'ACHAT DES PRODUIT DE cuisine',
                'description' => 'achat de dessirt',
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 1,
                'date_mise_ligne' => '2025-10-07',
                'date_limite_reception' => '2025-10-07',
                'statut' => 'livre_completement',
                'pieces_jointes' => '["pieces_jointes\\/bon_commandes\\/pQie69rQb6NXcpuIi38520vOgp91ERuSwJd3Eqnx.pdf"]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-07 12:36:50',
                'updated_at' => '2025-10-07 12:40:11',
                'deleted_at' => null
            ],
            [
                'id' => 10,
                'reference' => 'BC 01',
                'objet' => 1111,
                'description' => 'NNN',
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 2,
                'date_mise_ligne' => '2025-10-07',
                'date_limite_reception' => '2025-10-22',
                'statut' => 'attente_livraison',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-07 12:41:39',
                'updated_at' => '2025-10-07 12:44:16',
                'deleted_at' => null
            ],
            [
                'id' => 11,
                'reference' => 'BC 039',
                'objet' => 'ACHHAT',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 1,
                'date_mise_ligne' => '2025-10-07',
                'date_limite_reception' => '2025-10-22',
                'statut' => 'attente_livraison',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-07 12:42:23',
                'updated_at' => '2025-10-07 12:43:58',
                'deleted_at' => null
            ],
            [
                'id' => 12,
                'reference' => 'BC03',
                'objet' => 'JZDKJ',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 2,
                'date_mise_ligne' => '2025-10-08',
                'date_limite_reception' => '2025-10-22',
                'statut' => 'livre_completement',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-07 12:43:06',
                'updated_at' => '2025-10-07 13:31:08',
                'deleted_at' => null
            ],
            [
                'id' => 13,
                'reference' => 'BC2025-013',
                'objet' => 'Achat denrées – lot 13',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 1,
                'date_mise_ligne' => '2025-10-11',
                'date_limite_reception' => '2025-10-26',
                'statut' => 'livre_completement',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-11 17:30:09',
                'updated_at' => '2025-10-11 17:30:09',
                'deleted_at' => null
            ],
            [
                'id' => 14,
                'reference' => 'BC2025-014',
                'objet' => 'Achat denrées – lot 14',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 2,
                'date_mise_ligne' => '2025-10-11',
                'date_limite_reception' => '2025-10-26',
                'statut' => 'livre_completement',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-11 17:30:09',
                'updated_at' => '2025-10-11 17:30:09',
                'deleted_at' => null
            ],
            [
                'id' => 15,
                'reference' => 'BC2025-015',
                'objet' => 'Achat denrées – lot 15',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 1,
                'date_mise_ligne' => '2025-10-11',
                'date_limite_reception' => '2025-10-26',
                'statut' => 'livre_completement',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-11 17:30:09',
                'updated_at' => '2025-10-11 17:30:09',
                'deleted_at' => null
            ],
            [
                'id' => 16,
                'reference' => 'BC2025-016',
                'objet' => 'Achat denrées – lot 16',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 2,
                'date_mise_ligne' => '2025-10-11',
                'date_limite_reception' => '2025-10-26',
                'statut' => 'livre_completement',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-11 17:30:09',
                'updated_at' => '2025-10-11 17:30:09',
                'deleted_at' => null
            ],
            [
                'id' => 17,
                'reference' => 'BC2025-017',
                'objet' => 'Achat denrées – lot 17',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 1,
                'date_mise_ligne' => '2025-10-11',
                'date_limite_reception' => '2025-10-26',
                'statut' => 'livre_completement',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-11 17:30:09',
                'updated_at' => '2025-10-11 17:30:09',
                'deleted_at' => null
            ],
            [
                'id' => 18,
                'reference' => 'BC2025-018',
                'objet' => 'Achat denrées – lot 18',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 2,
                'date_mise_ligne' => '2025-10-11',
                'date_limite_reception' => '2025-10-26',
                'statut' => 'attente_livraison',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-11 17:30:09',
                'updated_at' => '2025-10-11 17:30:09',
                'deleted_at' => null
            ],
            [
                'id' => 19,
                'reference' => 'BC2025-019',
                'objet' => 'Achat denrées – lot 19',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 1,
                'date_mise_ligne' => '2025-10-11',
                'date_limite_reception' => '2025-10-26',
                'statut' => 'livre_completement',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-11 17:30:09',
                'updated_at' => '2025-10-11 18:12:01',
                'deleted_at' => null
            ],
            [
                'id' => 20,
                'reference' => 'BC2025-020',
                'objet' => 'Achat denrées – lot 20',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 2,
                'date_mise_ligne' => '2025-10-11',
                'date_limite_reception' => '2025-10-26',
                'statut' => 'attente_livraison',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-11 17:30:09',
                'updated_at' => '2025-10-11 17:30:09',
                'deleted_at' => null
            ],
            [
                'id' => 21,
                'reference' => 'GFDHGHJ',
                'objet' => 'VHJ?GJGJ',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 2,
                'date_mise_ligne' => '2025-10-11',
                'date_limite_reception' => '2025-10-26',
                'statut' => 'attente_livraison',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-11 19:55:43',
                'updated_at' => '2025-10-11 19:57:12',
                'deleted_at' => null
            ],
            [
                'id' => 22,
                'reference' => 'BC 3679',
                'objet' => 'ACHAT ....................',
                'description' => null,
                'categorie_principale_id' => 1,
                'nature_prestation_id' => 1,
                'fournisseur_id' => 2,
                'date_mise_ligne' => '2025-10-04',
                'date_limite_reception' => '2025-10-27',
                'statut' => 'livre_completement',
                'pieces_jointes' => '[]',
                'notes' => null,
                'created_by' => 2,
                'updated_by' => 1,
                'created_at' => '2025-10-12 18:25:37',
                'updated_at' => '2025-10-12 18:39:24',
                'deleted_at' => null
            ]
        ]);
    }
}